server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true

logging:
  level:
    root: INFO
    com.netflix: OFF
