spring:
  application:
    name: bun-backend
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: mongodb://root:example@mongo:27017/
    db: my-soccer-project

eureka:
  instance:
    hostname: bun-backend
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    root: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${MONGO_ATLAS_URI}
    db: my-soccer-project

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:bun-backend}
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

logging:
  level:
    root: WARN
